export const T = {
  teal: "var(--markly-teal)",
  tealDark: "var(--markly-teal-dark)",
  amber: "var(--markly-amber)",
  green: "var(--markly-green)",
  bg: "var(--markly-bg)",
  bgSec: "var(--markly-bg-sec)",
  card: "var(--markly-card)",
  cardElev: "var(--markly-card-elev)",
  border: "var(--markly-border)",
  borderStrong: "var(--markly-border-strong)",
  text: "var(--markly-text)",
  muted: "var(--markly-muted)",
  faint: "var(--markly-faint)",
  glowGreen: "var(--markly-glow-green)",
  glowBeige: "var(--markly-glow-beige)",
  accent: "var(--markly-accent)",
}
